repository: https://github.com/gavin-shaw/predictiv-lowdefy-blocks
revision: main
ingress:
  enabled: true
  hostname: blocks.k8s.syntegra.solutions
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls: true
mongodb:
  enabled: false
livenessProbe:
  enabled: false
  path: '/remoteEntry.js'
readinessProbe:
  enabled: false
  path: '/remoteEntry.js'
